<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\D2CSharpRTL\**\*.cs" Exclude="..\..\D2CSharpRTL\**\bin\**;..\..\D2CSharpRTL\**\obj\**" Link="D2CSharpRTL\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
